### ISSUE TITLE
Can you upload resources to another cloud like Gdrive,  Onedrive or Dropbox?

### ISSUE THREAD

**Issue by khiemledev** [luo3300612/image-captioning-DLCT#17]
In my country, the download speed from Baidu is very slow and I can't down needed resources. Can you please upload them to GDrive, OneDrive, or Dropbox? Thank you!

**Comment by luo3300612** [comment]
Sorry, since the whole file is ~70G. I am not able to afford to upload it to GDrive/OneDrive. But you can follow the Data preparation step. There are 5 keys in my hdf5 feature file. The first three keys can be obtained when extracting region features with [extract_region_feature.py](./others/extract_region_feature.py). The forth key can be obtained when extracting grid features with code in [grid-feats-vqa](https://github.com/facebookresearch/grid-feats-vqa). The last key can be obtained with [align.ipynb](./align/align.ipynb).

**Comment by khiemledev** [comment]
I do some tricks and successful to download the files. Thank you for your reply!

I have another question. Can you please tell me how to produce coco_train_ids.npy, coco_test_ids.npy, and coco_restval_ids.npy files for my own dataset already in COCO format?

**Comment by luo3300612** [comment]
coco_train_ids.npy is a (N,) numpy array where N=the number of images for training. It contains `id` to specify the image-text pair in `captions_train2014.json`:

```python
>>>import json
>>>info = json.load(open('captions_train2014.json'))
>>>annotations = info['annotations']
>>>print(annotations[0])
{'image_id': 318556, 'id': 48, 'caption': 'A very clean and well decorated empty bathroom'}
```

so the image feature is 318556_features/boxes/size/grids/mask, and the corresponding caption is 'A very clean and well decorated empty bathroom'.

However, since the code is highly limited to the COCO dataset, it is recommended to re-write [dataset.py](./data/dataset.py) for your own dataset. 

Or you need to create the hdf5, train/val/test_ids.npy and captions_train2014.json/captions_val2014.json file for your own dataset.

Hope it helps.

**Comment by khiemledev** [comment]
It's very helpful. Thank you very much!

**Comment by YuigaWada** [comment]
For those who don't have a Baidu account, I created a [mirror](https://keio.box.com/s/911narh5yrrp85s96cghu109bhg31hrv) of the data distributed on Baidu Pan. You can download the data from [this link](https://keio.box.com/s/911narh5yrrp85s96cghu109bhg31hrv) without login.
Use at your own risk :)
(also related to #36 issue)
